version: '3'
services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
    volumes:
      - ..:/workspace
    command: sleep infinity
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mmmmm
      MYSQL_DATABASE: guga
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: